### ISSUE TITLE
zoom level

### ISSUE THREAD

**Issue by astomas** [Twista/leaflet-google-places-autocomplete#7]
Is there a way to force the zoom level when selecting a place?
Thx

**Comment by Twista** [comment]
sorry for late response. In callback you have access to `map` object. Therefore you can call `map.setZoom(<desired zoom>)` easily :)

closing thins ticket (as it seems to be resolved)

**Comment by astomas** [comment]
Thank you. I tried:
"callback: function(location){map.setZoom(17);}" 
but no zoom on the selected place (and no console error). 
Did you manage to zoom on places?

**Comment by Twista** [comment]
Hey @astomas 

just tried in example and it works.

```
            new L.Control.GPlaceAutocomplete({
                callback: function(place){
                    var loc = place.geometry.location;
                    map.panTo([loc.lat(), loc.lng()]);
                    map.setZoom(18);
                }
            }).addTo(map);
```

can you share bit of your code eventualy ?

**Comment by astomas** [comment]
Hi
I tested and found that depending on the current zoom, when selecting a 'small' town (nimes, lussan..) it won't zoom to the correct place, when selecting a 'big' one (nice, paris..) zoom is good and it will then be good for 'small' towns too. No console error all the way. For the zoom to be correct for 'small' towns when opening my map,  I need to increase the current zoom from 10 to 13 but I can't ask that from my users.
My code is attached for testing. Thx.

**Comment by Twista** [comment]
That probably depends on the location you get out of the Google Autocomplete Service itself. 

Plugin itself is not doing any kind of geoding, just re-using results from GAC. (thats the place in callback)

What you can do is limit GAC to cities only, it might help. There is a list of options you can use for GAC https://developers.google.com/maps/documentation/javascript/places-autocomplete#add_autocomplete - and you can use `autocomplete_options` when creating instance of  `L.Control.GPlaceAutocomplete`

edit: also removed link from your comment to example because it contains your API key :)

**Comment by astomas** [comment]
Thanks,  can you do searches with types other than 'geocode' and 'establishment'? 
When I try new types ('locality', 'cities'..), no places are retrieved.
Example: autocomplete_options: {types:['administrative_area2'] }
My API key has rights to use Google Places API.

**Comment by astomas** [comment]
Hi. I managed to solve the problem without changing types autocomplete option. 
This code works whatever size of the town:
callback: function(place){ map.setZoom(16);  map.panTo([place.geometry.location.lat(), place.geometry.location.lng()]); }
Initially I put the setZoom AFTER the panTo now I force the zoom level above 13 before zooming and it works fine.
Thx for support
